In [1]:
import torch
import torchvision
import numpy as np

In [ ]:
a = torch.Tensor([1.])

In [ ]:
# tensor initialization
# directly from data
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
# from a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
# from another tensor
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n{x_ones}\n")

x_rand = torch.rand_like(x_data,dtype = torch.float)
print(f"Random Tensor: \n{x_rand}\n")

# with random or constant values:
# shape is the tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor:\n{rand_tensor}\n")
print(f"Ones Tensor:\n{ones_tensor}\n")
print(f"Zeros Tensor:\n{zeros_tensor}\n")


In [2]:
# tensor attributes: shape, device, datatype
tensor = torch.rand(2,3)
print(f"shape of tensor:{tensor.shape}")
print(f"datatype of tensor:{tensor.dtype}")
print(f"device tensor is stored on:{tensor.device}")

shape of tensor:torch.Size([2, 3])
datatype of tensor:torch.float32
device tensor is stored on:cpu


In [3]:
print(torch.version.cuda)
print(torch.__version__)

11.6
1.12.0+cu116


In [4]:
# tensor oprations
# comprehensively described here: https://pytorch.org/docs/stable/torch.html

# move tensor to GPU if available:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [8]:
# numpy-like usage of tensor
tensor = torch.ones(4,4)
tensor[1,:] = 3
print(f"modified tensor:\n{tensor}\n")

modified tensor:
tensor([[1., 1., 1., 1.],
        [3., 3., 3., 3.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([[1., 1., 1., 1.],
        [3., 3., 3., 3.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [18]:
tensor[1][3] = 0
t2 = torch.cat([tensor,tensor,tensor],dim=1)
print(t2)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [3., 3., 3., 0., 3., 3., 3., 0., 3., 3., 3., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [19]:
# multiplications of tensors
# the two methods below are equivalent
# element-wise product
print(f"tensor.mul(tensor)\n{tensor.mul(tensor)}\n")
# alternative syntax
print(f"tensor * tensor \n {tensor*tensor}\n")

tensor.mul(tensor)
tensor([[1., 1., 1., 1.],
        [9., 9., 9., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor * tensor 
 tensor([[1., 1., 1., 1.],
        [9., 9., 9., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])



In [22]:
# matrix multiplication
print(f"tensor.matmul(tensor):\n{tensor.matmul(tensor)}\n")
# alternative syntax
print(f"tensor @ tensor:\n{tensor@tensor}\n")

tensor.matmul(tensor):
tensor([[ 6.,  6.,  6.,  3.],
        [15., 15., 15.,  6.],
        [ 6.,  6.,  6.,  3.],
        [ 6.,  6.,  6.,  3.]])

tensor @ tensor.T:
tensor([[ 6.,  6.,  6.,  3.],
        [15., 15., 15.,  6.],
        [ 6.,  6.,  6.,  3.],
        [ 6.,  6.,  6.,  3.]])



In [23]:
# in-place operation
# operations that have a _ suffix are in-place.for example: x.add_(y), x.copy_(y), x.t_()
# in-place operations directly change the content of a tensor without making a copy of it.
# In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history.
print(tensor,"\n")
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1., 1.],
        [3., 3., 3., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

tensor([[6., 6., 6., 6.],
        [8., 8., 8., 5.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


In [25]:
# bridge with numpy
# Tensors on CPU and NumPy arrays share their underlying memory locations, and changing one will change the other.

# tensor to NumPy array
t = torch.ones(5)
n = t.numpy()
print(f"t:{t}")
print(f"n:{n}")
# a change in the tensor reflects in the NumPy array
t.add_(3)
print(f"t:{t}")
print(f"n:{n}")

t:tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]
t:tensor([4., 4., 4., 4., 4.])
n:[4. 4. 4. 4. 4.]


In [26]:
# NumPy array to tensor
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n,1,out=n)
print(f"t:{t}")
print(f"n:{n}")

t:tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n:[2. 2. 2. 2. 2.]


In [27]:
# seeding in pytorch
torch.manual_seed(1000)
r1 = torch.rand(2,2)
print(f"a random tensor r1:{r1}")
r2 = torch.rand(2,2)
print(f"another random tensor r2:{r2}")

torch.manual_seed(1000)
r3 = torch.rand(2,2)
print(f"r3 should be the same with r1{r3}")

a random tensor r1:tensor([[0.3189, 0.6136],
        [0.4418, 0.2580]])
another random tensor r2:tensor([[0.2724, 0.6261],
        [0.4410, 0.3653]])
r3 should be the same with r1tensor([[0.3189, 0.6136],
        [0.4418, 0.2580]])
